CREATE DATABASE scm OWNER scm ENCODING 'UTF8';
CREATE DATABASE rman OWNER rman ENCODING 'UTF8';
CREATE DATABASE hue OWNER hue ENCODING 'UTF8';
CREATE DATABASE metastore OWNER hive ENCODING 'UTF8';
CREATE DATABASE oozie OWNER oozie ENCODING 'UTF8';
CREATE DATABASE das OWNER das ENCODING 'UTF8';
CREATE DATABASE schemaregistry OWNER schemaregistry ENCODING 'UTF8';
CREATE DATABASE smm OWNER smm ENCODING 'UTF8';
CREATE DATABASE actmon OWNER actmon ENCODING 'UTF8';
CREATE DATABASE navaud OWNER navaud ENCODING 'UTF8';
CREATE DATABASE navmeta OWNER navmeta ENCODING 'UTF8';

CREATE DATABASE ranger OWNER rangeradmin ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE ranger TO rangeradmin;
